name : Index

on:
  pull_request:
    branches:
      - main
    paths:
      - 'index/**'
      - '.github/workflows/index-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Dockerized Bootstrapping from Git
      timeout-minutes: 20
      shell: bash
      run: |
        cd index
        make test-bootstrapping

    - name: Run Dockerized Tests for S3
      timeout-minutes: 20
      shell: bash
      run: |
        cd index
        make test-indexing
