name : Index Test and Push

env:
  IMAGE_NAME: opendatacube/datacube-index

on:
  pull_request:
    branches:
      - main
    paths:
      - 'index/**'
      - '.github/workflows/index-*'
  push:
    branches:
      - main
    paths:
      - 'index/**'
      - '.github/workflows/index-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Run Dockerized Bootstrapping from Git
      timeout-minutes: 20
      shell: bash
      run: |
        cd index
        make test-bootstrapping

    - name: Run Dockerized Tests for S3
      timeout-minutes: 20
      shell: bash
      run: |
        cd index
        make test-indexing

  push:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required for requesting the JWT
      packages: write  # This is required for pushing to ghcr
      attestations: write # This is required for pushing the attestation
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Verify Changed files
      uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      id: verify-changed-version
      with:
        files: |
            index/version.txt

    - name: Run step only when version.txt change.
      if: steps.verify-changed-version.outputs.any_changed == 'true'
      run: |
        echo "VERSION=$(cat index/version.txt)" >> $GITHUB_ENV

    - name: echo dev version for dockhub image tagging
      if: steps.verify-changed-version.outputs.any_changed == 'false'
      run: |
        echo "VERSION=$(cat index/version.txt).dev${{ github.run_id }}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

    # Push to both Dockerhub and GitHub Container Registry
    - name: Build Docker
      id: push
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: "{{defaultContext}}:index"
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:latest
          ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Attest Docker image
      uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
      id: attest
      with:
        subject-name: ghcr.io/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
