name : Index

on:
  pull_request:
    branches:
      - main
    paths:
      - 'index/**'
      - '.github/workflows/index-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Dockerized Bootstrapping from Git
      timeout-minutes: 20
      shell: bash
      env:
        PRODUCT_CATALOG : https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-products.csv
        METADATA_CATALOG : https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-metadata.yaml
      run: |
        cd index
        make test-bootstrapping

    - name: Run Dockerized Tests for S3
      timeout-minutes: 20
      shell: bash
      run: |
        cd index
        make test-indexing
