name : Statistician Test and Push

env:
  IMAGE_NAME: opendatacube/datacube-statistician

on:
  pull_request:
    paths:
      - 'statistician/**'
      - '.github/workflows/statistician-*'
  push:
    branches:
      - main
    paths:
      - 'statistician/**'
      - '.github/workflows/statistician-*'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: lint Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: statistician/Dockerfile
        ignore: DL3008,DL3002,DL3013,DL3059,SC2102

    - name: Build Statistician image
      timeout-minutes: 20
      shell: bash
      run: |
        cd statistician
        docker-compose build

    - name: Run Dockerized Tests for Statistician
      shell: bash
      run: |
        cd statistician
        make test

  push:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag for this build if it exists
      run: |
        echo "VERSION=$(cat statistician/version.txt)" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::538673716275:role/github-ecr
        aws-region: ap-southeast-2

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image to ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ env.VERSION }}
      run: |
        cd ./statistician
        docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:$IMAGE_TAG .
        docker push $REGISTRY/${{ env.IMAGE_NAME }}:$IMAGE_TAG
        docker tag $REGISTRY/${{ env.IMAGE_NAME }}:$IMAGE_TAG $REGISTRY/${{ env.IMAGE_NAME }}:latest
        docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest
