name : Statistician

on:
  push:
    branches:
      - main
    paths:
      - 'statistician/**'
      - '.github/workflows/statistician-*'

env:
  IMAGE_NAME: opendatacube/datacube-statistician

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag for this build if it exists
      run: |
        echo "VERSION=$(cat statistician/version.txt)" >> $GITHUB_ENV

    - name: Build and Push unstable Docker Image from PR / Push to Master
      uses: whoan/docker-build-with-cache-action@v4
      with:
        context: statistician
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        image_tag: latest,${{ env.VERSION }}
