---
name: Statistician docker check

on:
  pull_request:
    paths:
      - '.github/workflows/statistician-dive.yml'
      - 'statistician/**'

  push:
    paths:
      - '.github/workflows/statistician-dive.yml'
      - 'statistician/**'

env:
  ORG: odc
  IMAGE: statistician 

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: statistician/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${ORG}/${IMAGE}:_build ./statistician/

      - name: Dive
        uses: yuichielectric/dive-action@0.0.3
        with:
          image: ${{ env.ORG }}/${{ env.IMAGE}}:_build
          config-file: ${{ github.workspace }}/statistician/dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image size check
        uses: wemake-services/docker-image-size-limit@master
        with:
          image: ${{ env.ORG }}/${{ env.IMAGE}}:_build
          size: "2 GiB"
